## Site Info
title:              "Blog testing"
description:        "My blog testing"

website:
    # This should point to your website source.
    source:     https://github.com/frnmst/the-flux-of-thought
    license:
        url: "https://creativecommons.org/licenses/by-sa/4.0/"
        name: "CC-BY-SA 4.0"

software:
    # These should point to the-flux-of-thought repository.
    home: https://github.com/frnmst/the-flux-of-thought
    version: "0.1.0"
    # The following is used along the version variable to build the
    # software version url.
    release_base_url: "https://github.com/frnmst/the-flux-of-thought/releases/tag"

author:
    name: "Franco Masotti"
    email: "franco.masotti@live.com"

## Site Settings
# Base URL must end WITHOUT a slash, default: ""
baseurl:            "/the-flux-of-thought"

# Post permalink. If you change this you must
# modify all the occurencies manually.
permalink:          /notes/:title
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/Rome
uture:             true

## Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

excerpts:
    enabled:        true
    start:          "<!--excerpt_start-->"
    end:            "<!--excerpt_end-->"
    words:          20

limit_tag_links:     16
tags:
    score:
        min:       2
    # Set the following to false to avoid limiting the tag links.
    link_limit:     16

meta:
    description_words:         140
    excerpt_words:             140
    site_description_words:    140

anchor_headings:
    enabled:         true
    character:       "&#182;"
    min:             1
    max:             6

    # Puts the anchor heading before the title if set to true.
    before:          false

# Keep comments hidden
collections:
  comments:
    output:         false
  pages:
    output:         false
  media:
    output:         true
  assets:
    output:         true

## Page names
defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
      is_post:      true
  -
    scope:
      path:         "_pages/index.md"
    values:
      is_home:      true
  -
    scope:
      path:         "_pages/404.md"
    values:
      is_404:       true
  -
    scope:
      path:         "_pages/tags.md"
    values:
      is_tags:       true
  -
    scope:
      path:         "_pages/sitemap.md"
    values:
      is_sitemap:   true
  -
    scope:
      path:         "comments"
      type:         comments
    values:
      layout:       comment
      is_comment:   true

## Other Params
include:            [ "_pages" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "Makefile" ]

## Ruby gems
plugins:
  - jekyll-sitemap
